### ISSUE TITLE
Add new arithmetic instructions to all interpreter variants

### ISSUE THREAD

**Issue by grigory-rechistov** [grigory-rechistov/interpreters-comparison#1]
Currently the VM has 18 instructions. The task is to add and test implementation of new instructions:
1. `And` (a b -- a & b) - logical AND
2. `Or` (a b  -- a | b) - logical OR
3. `Xor` (a b  -- a ^ b) - logical Exsclusive OR
4. `SHL` (a shift -- a << shift) - Shift left
5. `SHR` (a shift -- a >> shift) - Shift right
6. `SQRT` (x -- √x̅) - find integer square root
7. `Rot`   ( a b c -- b c a ) - rotate three top items on the stack
8. `Pick` ( a0 .. an n -- a0 .. an a0 ) - pick n-th item from the stack

**Comment by kurapov-peter** [comment]
I'll take it!

**Comment by grigory-rechistov** [comment]
Could you please provide your name? I cannot deduce it from your nickname.

**Comment by kurapov-peter** [comment]
Oops, Petr

**Comment by grigory-rechistov** [comment]
Assigned to Kurapov, Petr
