### ISSUE TITLE
Add procedure call return mechanism to several variants of interpreters

### ISSUE THREAD

**Issue by grigory-rechistov** [grigory-rechistov/interpreters-comparison#2]
Currently the VM lacks any procedure mechanism. The task is to add implementation and tests:
1. Add a separate _return stack_ to store addresses
2. Add new instructions:
   - `call imm` - pushes current PC on return stack and jumps to PC+imm
   - `ret` - pops new PC value from stack

**Comment by Vsevolod-Livinskij** [comment]
Assign it to me, please.

**Comment by grigory-rechistov** [comment]
Done
