### ISSUE TITLE
Add new benchmarks to the Program suite

### ISSUE THREAD

**Issue by grigory-rechistov** [grigory-rechistov/interpreters-comparison#4]
Add one to three programs to the suite.
1. Calculate an approximation of square root of given number by Newton-Raphson method
2. Sort an array by any known method (bubble, quicksort, heapsort etc)
3. Looking for a substring match inside a given string

Additionally, any other computationally-intensive algorithm will be good as well

**Comment by sash-tsvet** [comment]
Attach it to me please

**Comment by grigory-rechistov** [comment]
The solution is in https://github.com/grigory-rechistov/interpreters-comparison/tree/sash-tsvet-task-04
