### ISSUE TITLE
Make project code build and work as Microsoft Visual Studio project

### ISSUE THREAD

**Issue by grigory-rechistov** [grigory-rechistov/interpreters-comparison#5]
Currently the project is only buildable/runnable on Linux GCC/ICC (possibly Clang) toolchain and buildable (with limited operation supported) on Cygwin on Windows. Native Windows support is needed.

The task is:
1. Use latest MS VS to create a set of projects/solutions for the code.
2. Use MS compiler to build as many variants of interpreters as possible.
3. Make tests run for them

**Comment by Thar0l** [comment]
I`ve installed VS2015, so assign it to me, please.

**Comment by grigory-rechistov** [comment]
Closed in #16
