### ISSUE TITLE
Create fully-inlined translated version

### ISSUE THREAD

**Issue by grigory-rechistov** [grigory-rechistov/interpreters-comparison#8]
Currently `translated` variant uses `MOV; CALL` generated sequences to drive simulation to individual service routines. A fully inlined variant should insert copies of service routines in the generated code section. This will save a pair of call/return.

The steps required to complete the task:
1. Create _relocatable_ service routines (possibly in assembler)
2. Make sure the state is passed and modified correctly
2. Modify the `translated` to copy capsules instead of `CALL` machine code.

**Comment by Vipon** [comment]
I take it.

**Comment by grigory-rechistov** [comment]
Closed in #23
